// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 002_logs.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs (id, date, color_depth, user_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3
)
RETURNING id, date, color_depth, confirmed, user_id
`

type CreateLogParams struct {
	Date       time.Time
	ColorDepth int32
	UserID     uuid.UUID
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createLog, arg.Date, arg.ColorDepth, arg.UserID)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.ColorDepth,
		&i.Confirmed,
		&i.UserID,
	)
	return i, err
}
